# https://answers.gazebosim.org//question/5468/gazebo_ros_pkgs-no-p-gain-specified-for-pid-in-positionjointinterface/

gazebo_ros_control/pid_gains:
  j1: {p: 10.0, i: 0.0, d: 1.0}
  j2: {p: 10.0, i: 0.0, d: 1.0}
  j3: {p: 10.0, i: 0.0, d: 1.0}
  j4: {p: 10.0, i: 0.0, d: 1.0}